server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
      - id: people-service
        uri: lb://people-service/
        predicates:
          - Path=/people/**
      - id: job-service
        uri: lb://job-service/
        predicates:
          - Path=/jobs/**
      - id: residencies-service
        uri: lb://residencies-service/
        predicates:
          - Path=/residencies/**
    discovery:
      locator:
        enable: true