server:
  port: 8081
spring:
  cloud:
    config:
      server:
        bootstrap: true
        git:
          default-label: config-server
          uri: https://github.com/ortegafran97/PeopleMicroservices
          search-paths: config-data
  application:
    name: config-service

